Add New Method
Net-532/kakadu pull request #172
Opened 2024-05-14 11:46 UTC by Stas0321

2024-05-14 12:05 UTC, Morph1y requested changes
Друже, будь ласка. Виправ дурні помилки

2024-05-14 12:05 UTC, Morph1y commented on Backend/Backend/Repositories/OrderRepositoryXML.cs
> +            XmlNode UpdateAtElemant = doc.CreateElement("UpdatedAt");
Слиш бобер переіменуй.
UpdateAtElemant на UpdateAtElement

2024-05-14 12:05 UTC, Morph1y commented on Backend/Backend/Repositories/OrderRepositoryXML.cs
> +            orderElement.AppendChild(orderDateElement);
ШО це, ти дурк? передєливай.!   orderDateElement заміни на  orderElement.AppendChild(orderUpdateAtElement);

2024-05-14 12:15 UTC, Stas0321 commented on Backend/Backend/Repositories/OrderRepositoryXML.cs
> +            orderElement.AppendChild(orderDateElement);
Навіщо писати orderUpdateAtElement якщо можна прсто  UpdateAtElement

2024-05-15 16:18 UTC, mvoronovpolytech requested changes

2024-05-15 16:18 UTC, mvoronovpolytech commented on Backend/Backend/Entities/Order.cs
> +        public DateTime UpdatedAt { get; set; }
Добав ще, будь ласка, в OrderRequestProcessor рядок
`order.UpdatedAt = order.OrderDate;`
після 
`order.Status = "Processing";`

2024-05-16 08:27 UTC, mvoronovpolytech approved these changes

2024-05-16 08:33 UTC, Morph1y approved these changes
Normas

2024-05-16 08:34 UTC, Benswors approved these changes

2024-05-16 11:08 UTC, merged