check style
Net-532/kakadu pull request #224
Opened 2024-05-29 13:24 UTC by cultureowo

2024-05-29 17:26 UTC, mvoronovpolytech requested changes

2024-05-29 17:26 UTC, mvoronovpolytech commented on kiosk/index.html
> +  <div class="btn-check">
Кнопка "Друк" пропала (

2024-05-29 17:26 UTC, mvoronovpolytech commented on kiosk/assets/css/check.css
> +    text-align: left;
не потрібно

2024-05-29 17:26 UTC, mvoronovpolytech commented on kiosk/assets/css/check.css
> +    background-color: #f9f9f9;
не потрібно

2024-05-29 17:26 UTC, mvoronovpolytech commented on kiosk/assets/css/check.css
> -.container-receipt {
![зображення](https://github.com/Net-532/kakadu/assets/157631979/7ce1cc30-5a35-4c4f-b2e2-dcf253fc8f7a)

2024-05-29 17:26 UTC, mvoronovpolytech commented on kiosk/assets/css/check.css
> -.container-receipt {
1. пропоную забрати слово Адреса
2. постав пробіли між словами
3. форматування ціни з копійками
4. можеш ще повернути як було: назва товару та ціна були на одному рядку. якщо розбивати на 2 рядки, то нам потрібно ще на бекенді змінювати друк чеку, що зараз не дуже хочеться робити

2024-05-29 17:26 UTC, mvoronovpolytech commented on kiosk/assets/css/check.css
> +    font-size: 16px;
верни font-family: "Kyiv", serif;

2024-05-29 17:26 UTC, mvoronovpolytech commented on kiosk/assets/css/check.css
> +}
Шрифт виставлений на .receipt, цього достатньо. Можеш повидаляти з receipt-info, receipt-thanks, .container-receipt

2024-05-29 17:26 UTC, mvoronovpolytech commented on kiosk/assets/JavaScript/cart.js
> +      <center>
повидаляй ще, будь ласка, `center` елемент, та додай центрування тексту до receipt-info та receipt-thanks

2024-05-30 20:20 UTC, mvoronovpolytech requested changes

2024-05-30 20:20 UTC, mvoronovpolytech commented on kiosk/assets/JavaScript/cart.js
> +    return totalSum.toFixed(2);
чому не використати функцію `formatPrice`, яку ти зробила ?

2024-05-30 20:20 UTC, mvoronovpolytech commented on kiosk/assets/JavaScript/cart.js
> +              <div class="price"> ${item.quantity} x ${formatPrice(item.price)} грн</div>
Забери, будь ласка, `грн`

2024-06-02 13:55 UTC, mvoronovpolytech requested changes

2024-06-02 13:55 UTC, mvoronovpolytech commented on kiosk/assets/css/check.css
>  }
цей стиль можна видалити

2024-06-02 13:55 UTC, mvoronovpolytech commented on kiosk/assets/css/check.css
>  }
це можна об'єднати

```
.name p,
.price p {
    margin: 0;
}
```

2024-06-02 13:55 UTC, mvoronovpolytech commented on kiosk/assets/JavaScript/cart.js
> +                <p class="card-text" id="cart-item-price">${formatPrice(item.price)} грн</p>
постав, ще будь ласка, пробіл між перед знаком оклику в `Дякуємо за покупку !`

2024-06-05 10:14 UTC, cultureowo commented on kiosk/assets/css/check.css
> +    background-color: #f9f9f9;
fixed

2024-06-05 10:17 UTC, cultureowo commented on kiosk/assets/JavaScript/cart.js
> +      <center>
fixed

2024-06-05 12:34 UTC, mvoronovpolytech approved these changes

2024-06-05 12:35 UTC, merged