Style/datagrid
Net-532/kakadu pull request #277
Opened 2024-06-11 20:21 UTC by Stas0321

2024-06-11 20:55 UTC, mvoronovpolytech requested changes

2024-06-11 20:55 UTC, mvoronovpolytech commented on Backoffice/App.xaml
> +            <Setter Property="TextElement.FontWeight" Value="Semibold"/>
Видали, будь ласка, `<Setter Property="TextElement.FontWeight" Value="Semibold"/>`

2024-06-11 20:55 UTC, mvoronovpolytech commented on Backoffice/Views/Orders.xaml
> +                <DataGrid x:Name="dataGrid" Grid.Row="1" Style="{StaticResource Grid}" AutoGenerateColumns="False" IsReadOnly="True" ItemsSource="{Binding Orders}">
Повидаляй, будь ласка, `AutoGenerateColumns="False" IsReadOnly="True"` оскільки ти ці властивості добавив в стилі гріда.
Подивись ще grid в  Products, Users

2024-06-11 20:55 UTC, mvoronovpolytech commented on Backoffice/App.xaml
> +            <Setter Property="BorderBrush" Value="#CDD1DE"/>
немає змісту, оскільки BorderThickness=0

2024-06-11 20:55 UTC, mvoronovpolytech commented on Backoffice/App.xaml
> +            <Setter Property="Foreground" Value="#1C2A53"/>
Теж можна забрати `<Setter Property="Foreground" Value="#1C2A53"/>`, оскільки ми перевизначаємо в заголовках та рядках

2024-06-11 20:57 UTC, mvoronovpolytech commented on Backoffice/App.xaml
> +            <Setter Property="Foreground" Value="DarkGray"/>
і додай жирність шрифта Semibold

2024-06-11 22:11 UTC, mvoronovpolytech requested changes

2024-06-11 22:11 UTC, mvoronovpolytech commented on Backoffice/App.xaml
> +            </Style.Triggers>
в тебе щось тут не так, треба так

```
  <Style TargetType="DataGridRow">
      <Setter Property="FontSize" Value="14"/>
      <Setter Property="Foreground" Value="#555F7E"/>
      <Style.Triggers>
          <Trigger Property="IsMouseOver" Value="True">
              <Setter Property="Background" Value="#FFFCF8"/>
              <Setter Property="Cursor" Value="Hand"/>
          </Trigger>
      </Style.Triggers>
  </Style>
```

2024-06-11 22:11 UTC, mvoronovpolytech commented on Backoffice/App.xaml
> +            <Setter Property="TextElement.Foreground" Value="#555F7E"/>
видали будь ласка ```


            <Setter Property="TextElement.FontSize" Value="14"/>
            <Setter Property="TextElement.Foreground" Value="#555F7E"/>
```

2024-06-11 22:11 UTC, mvoronovpolytech commented on Backoffice/App.xaml
> +            <Setter Property="AlternatingRowBackground" Value="#F5F5F5"/>
все таки IsReadOnly треба поставити

` <Setter Property="IsReadOnly" Value="True"/>`

2024-06-12 11:15 UTC, Stas0321 commented on Backoffice/App.xaml
> +            </Style.Triggers>
done

2024-06-12 11:15 UTC, Stas0321 commented on Backoffice/App.xaml
> +            <Setter Property="TextElement.Foreground" Value="#555F7E"/>
done

2024-06-12 12:50 UTC, merged