Button
Net-532/kakadu pull request #280
Opened 2024-06-12 12:44 UTC by Stas0321

2024-06-12 19:33 UTC, mvoronovpolytech requested changes

2024-06-12 19:33 UTC, mvoronovpolytech commented on Backoffice/Backoffice.sln
> +EndProject
Шось це мені не подобається. Можеш видалити?

2024-06-12 19:33 UTC, mvoronovpolytech commented on Backoffice/Views/Orders.xaml.cs
> -                }
try catch залиши

2024-06-12 19:33 UTC, mvoronovpolytech commented on Backoffice/Views/Products.xaml
>                          <DataGridTextColumn Width="200">
Давай ширину колонки ціни зменшимо до 100

2024-06-12 19:33 UTC, mvoronovpolytech commented on Backoffice/Views/Products.xaml.cs
> -            }
Це верни як було

2024-06-12 19:33 UTC, mvoronovpolytech commented on Backoffice/Views/Users.xaml.cs
> -            }
Поверни, будь ласка, ця зміна не стосується виділеного рядка

2024-06-13 06:44 UTC, mvoronovpolytech commented on Backoffice/Views/Orders.xaml.cs
> +            PrintButton.IsEnabled = isOrderSelected;
В мене ця штука на працює (

2024-06-13 12:58 UTC, Stas0321 commented on Backoffice/Backoffice.sln
> +EndProject
done

2024-06-13 14:42 UTC, mvoronovpolytech approved these changes

2024-06-13 14:43 UTC, merged