Create order queue
Net-532/kakadu pull request #74
Opened 2024-03-26 10:27 UTC by Stas0321

2024-03-27 15:07 UTC, mvoronovpolytech requested changes

2024-03-27 15:07 UTC, mvoronovpolytech commented on Backend/OrderQueue/OrderQueue/MainWindow.xaml
> +        </Border>-->
Видали, будь ласка, закоментований код

2024-03-27 15:07 UTC, mvoronovpolytech commented on Backend/OrderQueue/OrderQueue/MainWindow.xaml.cs
> +namespace OrderQueue
Зміни, будь ласка, неймспейс на `namespace Kakadu.OrderQueue`

2024-03-27 15:07 UTC, mvoronovpolytech commented on Backend/OrderQueue/OrderQueue/MainWindow.xaml.cs
> +using System.Windows.Shapes;
Поивидаляй, будь ласка, зайві імпорти

2024-03-27 15:07 UTC, mvoronovpolytech commented on Backend/OrderQueue/OrderQueue/MainWindow.xaml.cs
> +            ResizeMode = ResizeMode.NoResize;
Мені здається, це можна зробити простіше, а саме встановити ці властивості в xaml файлі

2024-03-27 15:07 UTC, mvoronovpolytech commented on Backend/OrderQueue/OrderQueue/App.xaml.cs
> +namespace OrderQueue
Зміни, будь ласка, неймспейс на namespace `Kakadu.OrderQueue`

2024-03-27 15:07 UTC, mvoronovpolytech commented on Backend/OrderQueue/OrderQueue/MainWindow.xaml
> +            <StackPanel>
Без цього <StackPanel> можна обійтися?

2024-03-27 15:07 UTC, mvoronovpolytech commented on Backend/OrderQueue/OrderQueue/MainWindow.xaml
> +            <StackPanel>
Без цього <StackPanel> можна обійтися?

2024-04-02 12:08 UTC, Stas0321 commented on Backend/OrderQueue/OrderQueue/MainWindow.xaml
> +            <StackPanel>
Я використовую WrapPanel для того щоб текст був в колонках

2024-04-02 12:48 UTC, mvoronovpolytech commented on Backend/OrderQueue/OrderQueue/MainWindow.xaml
> +            <StackPanel>
WrapPanel потрібен для переміщення елементів керування у другий стовпчик

2024-04-02 18:14 UTC, mvoronovpolytech approved these changes

2024-04-02 18:15 UTC, merged