Feature/cart
Net-532/kakadu pull request #87
Opened 2024-04-16 17:03 UTC by Xtrayck

2024-04-17 19:21 UTC, mvoronovpolytech requested changes

2024-05-06 08:21 UTC, mvoronovpolytech requested changes

2024-05-06 08:21 UTC, mvoronovpolytech commented on kiosk/index.html
> +  <div class="offcanvas-xxl offcanvas-bottom" tabindex="-1" id="offcanvasBottom">
Кошик не закривається якщо клікнути на хрестик.
Що це пофіксити - зміни, будь ласка, клас на `class="offcanvas offcanvas-bottom"`

2024-05-06 08:21 UTC, mvoronovpolytech commented on kiosk/assets/css/style.css
> +          }
Видали, будь ласка, це вже буде не  потрібно, післся зміни класу в index.html

2024-05-06 08:21 UTC, mvoronovpolytech commented on kiosk/assets/JavaScript/cart.js
> +}
Добав, будь ласка, користувачу повідомлення "Добавлено в кошик!"

2024-05-06 08:21 UTC, mvoronovpolytech commented on kiosk/assets/JavaScript/products.js
> +            renderCart();
Можливо, краще спочатку, викликати `renderCart()`, а потім вже показувати кошик

2024-05-06 08:21 UTC, mvoronovpolytech commented on kiosk/assets/JavaScript/cart.js
> +        addToCart({ id: item.id });
Давай трохи вдосконалимо код, замість `{ id: item.id }` ти можеш передати просто `item`

2024-05-06 08:21 UTC, mvoronovpolytech commented on kiosk/assets/JavaScript/cart.js
> +        removeFromCart({ id: item.id });
Теж саме, що і в  `addToCart({ id: item.id });`, передай просто `item`

2024-05-06 08:21 UTC, mvoronovpolytech commented on kiosk/assets/JavaScript/cart.js
> +        removeItemFromCart({ id: item.id });
Теж саме, що і в  `addToCart({ id: item.id });`, передай просто `item`

2024-05-06 08:46 UTC, NovileOrange commented on kiosk/assets/css/style.css
> +          }
Воно вот так виглядає навіть після змін

![photo_2024-05-06_11-42-50](https://github.com/Net-532/kakadu/assets/119979889/16011e73-8d70-4bec-8984-f8d2715c62c8)

2024-05-06 10:40 UTC, mvoronovpolytech commented on kiosk/assets/css/style.css
> +          }
Хмм, погано .. я подивлюсь що не так

2024-05-06 11:42 UTC, mvoronovpolytech commented on kiosk/assets/css/style.css
> +          }
Вирішили, що стилі будуть виправлені в https://github.com/Net-532/kakadu/issues/68#issue-2203976689

2024-05-06 11:42 UTC, mvoronovpolytech approved these changes

2024-05-06 11:42 UTC, merged