Logger for WebServer
Net-532/kakadu pull request #89
Opened 2024-04-24 16:57 UTC by r0kten

Added logging configuration for the web server, logs are written to a file called log20240424.txt on the path: WebServer\bin\Debug\net8.0

2024-04-24 20:07 UTC, mvoronovpolytech requested changes

2024-04-24 20:07 UTC, mvoronovpolytech commented on WebServer/WebServer.cs
> +            Log.Information($"Web Server Running on {address.ToString()} on port {port}...");
У логерів є багато перевантажених методів. Тому краще використовувати їх, ніж інтерполяцію строки.
Наприклад можна спростити так : 
```
 Log.Information("Web Server Running on {Address} on port {Port}...", address, port);
```
Почитати документацію можна тут https://github.com/serilog/serilog/wiki/Writing-Log-Events

2024-04-25 19:14 UTC, r0kten commented
Зробив новий коміт зі змінами

2024-04-26 14:31 UTC, mvoronovpolytech approved these changes

2024-04-26 14:31 UTC, merged